{
  "hash": "433416c8edabe9194ee93ac857916d32",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Henry Yang\"\ndate: 12/10/2025\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(ggplot2)\nlibrary(knitr)\nlibrary(tidyverse)\nlibrary(tidycensus)\nlibrary(tigris)\nlibrary(here)\n\n# Load spatial data\npa_counties <- counties(state = \"PA\", cb = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |                                                                      |   1%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |=====                                                                 |   8%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |=======                                                               |  11%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |============                                                          |  18%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |==============                                                        |  21%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |================                                                      |  24%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |===================                                                   |  28%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |=====================                                                 |  31%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |=======================                                               |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |=======================                                               |  34%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |========================                                              |  35%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===========================                                           |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |============================                                          |  41%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |==============================                                        |  44%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |===============================                                       |  45%\n  |                                                                            \n  |================================                                      |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |=================================                                     |  48%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |===================================                                   |  51%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |======================================                                |  55%\n  |                                                                            \n  |=======================================                               |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |========================================                              |  58%\n  |                                                                            \n  |=========================================                             |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |==========================================                            |  61%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |============================================                          |  64%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |=============================================                         |  65%\n  |                                                                            \n  |==============================================                        |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |===============================================                       |  68%\n  |                                                                            \n  |================================================                      |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |=================================================                     |  71%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |===================================================                   |  74%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |====================================================                  |  75%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |======================================================                |  78%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |========================================================              |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |========================================================              |  81%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |=========================================================             |  82%\n  |                                                                            \n  |==========================================================            |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |==========================================================            |  84%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===========================================================           |  85%\n  |                                                                            \n  |============================================================          |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |==============================================================        |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |===============================================================       |  91%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |====================================================================  |  98%\n  |                                                                            \n  |===================================================================== |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================|  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\npa_tracts <- tracts(state = \"PA\", cb = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |============                                                          |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |==============                                                        |  21%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |========================                                              |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |============================                                          |  41%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |===============================                                       |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |=================================                                     |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |===================================                                   |  51%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |=====================================                                 |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |=======================================                               |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |=========================================                             |  58%\n  |                                                                            \n  |==========================================                            |  59%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |==============================================                        |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |=================================================                     |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |==========================================================            |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |===============================================================       |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |=================================================================     |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |===================================================================   |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |===================================================================== |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_read(here(\"data\", \"hospitals.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `/Users/henryyang/Desktop/MasterStuff/CPLN5920/Code/portfolio-setup-henryyzh1/Labs/lab_2/data/hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check that all data loaded correctly\nst_crs(pa_counties)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: NAD83 \n  wkt:\nGEOGCRS[\"NAD83\",\n    DATUM[\"North American Datum 1983\",\n        ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4269]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(pa_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: NAD83 \n  wkt:\nGEOGCRS[\"NAD83\",\n    DATUM[\"North American Datum 1983\",\n        ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4269]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(hospitals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\n  - 223 hospitals.\n- How many census tracts?\n  - 3,445 tracts.\n- What coordinate reference system is each dataset in?\n  - Counties and tracts are using NAD 83, hospitals are using WGS 84.\n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\npa_acs_vars <- c(\n  total_pop = \"B01003_001\",\n  median_income = \"B19013_001\",\n  age65_66_m = \"B01001_020\",\n  age67_69_m = \"B01001_021\",\n  age70_74_m = \"B01001_022\",\n  age75_79_m = \"B01001_023\",\n  age80_84_m = \"B01001_024\",\n  age85_over_m = \"B01001_025\",\n  age65_66_f = \"B01001_044\",\n  age67_69_f = \"B01001_045\",\n  age70_74_f = \"B01001_046\",\n  age75_79_f = \"B01001_047\",\n  age80_84_f = \"B01001_048\",\n  age85_over_f = \"B01001_049\"\n)\n\npa_acs <- get_acs(\n  geography = \"tract\",\n  variables = pa_acs_vars,\n  state = \"PA\",\n  year = 2022,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\npa_acs <- pa_acs %>%\n  mutate(pop65plusE = age65_66_mE + age67_69_mE + age70_74_mE + age75_79_mE + age80_84_mE + age85_over_mE + age65_66_fE + age67_69_fE + age70_74_fE + age75_79_fE + age80_84_fE + age85_over_fE)\n\n# Join to tract boundaries\npa_tracts_acs <- pa_tracts %>%\n  left_join(\n    pa_acs %>% \n      select(GEOID, total_popE, median_incomeE, pop65plusE),\n    by = \"GEOID\"\n  )\n\nsum(is.na(pa_tracts_acs$median_incomeE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(pa_tracts_acs$median_incomeE, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70188\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n  - 2022.\n- How many tracts have missing income data?\n  - 62.\n- What is the median income across all PA census tracts?\n - $70,188.\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\nq1_income <- quantile(pa_tracts_acs$median_incomeE, \n                      probs = 0.25, na.rm = TRUE)\n\nincome_thres <- 56000\nelder_thres <- 0.20\n\npa_tracts_acs <- pa_tracts_acs %>%\n  mutate(\n    pct65plus = pop65plusE / total_popE\n  )\n\nvulnerable_tracts <- pa_tracts_acs %>%\n  filter(\n    median_incomeE < income_thres,\n    pct65plus > elder_thres\n  )\n\nn_vulnerable <- nrow(vulnerable_tracts)\nn_total <- nrow(pa_tracts_acs)\npct_vulnerable <- round(100 * n_vulnerable / n_total, 1)\n\nn_vulnerable; pct_vulnerable\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 273\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.9\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\n  - $56,000. This corresponds approximately to the first percentile (Q1) of median household income across Pennsylvania tracts (about $55,924).\n- What elderly population threshold did you choose and why?\n  - 20%. This cutoff is commonly used in demographic and policy research to designate “aging communities”.\n- How many tracts meet your vulnerability criteria?\n  - 273.\n- What percentage of PA census tracts are considered vulnerable by your definition?\n  - 7.9%.\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\nhospitals_proj <- st_transform(hospitals, 3365)\npa_tracts_proj <- st_transform(pa_tracts_acs, 3365)\n\n# Calculate distance from each tract centroid to nearest hospital\nvulnerable_tracts_proj <- pa_tracts_proj %>%\n  filter(median_incomeE < 56000, pop65plusE / total_popE > 0.2)\n\nvulnerable_centroids <- st_centroid(vulnerable_tracts_proj)\n\ndist_matrix <- st_distance(vulnerable_centroids, hospitals_proj)\nnearest_ft <- apply(dist_matrix, 1, min)\nnearest_mi <- as.numeric(nearest_ft) / 5280\n\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(nearest_hospital_dist = nearest_mi)\n\navg_dist <- round(mean(nearest_mi, na.rm = TRUE), 1)\nmax_dist <- round(max(nearest_mi, na.rm = TRUE), 1)\nn_far <- sum(nearest_mi > 15, na.rm = TRUE)\n\navg_dist; max_dist; n_far\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.5\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25.6\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14\n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n- Explain why you chose your projection\n  - EPSG:3365 (NAD83(HARN) / Pennsylvania South (ftUS)), which is a state-specific projected CRS for Pennsylvania. This system is designed for accurate distance and area measurements within the state.\n- What is the average distance to the nearest hospital for vulnerable tracts?\n  - 4.5 miles.\n- What is the maximum distance?\n  - 25.6 miles.\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n  - 14.\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(underserved = nearest_hospital_dist > 15)\n\nn_underserved <- sum(vulnerable_tracts_proj$underserved, na.rm = TRUE)\npct_underserved <- round(100 * n_underserved / n_vulnerable, 1)\n\nn_underserved; pct_underserved\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.1\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved?\n  - 14.\n- What percentage of vulnerable tracts are underserved?\n  - 5.1%.\n- Does this surprise you? Why or why not?\n  - It is not very surprising, because Pennsylvania has many hospitals clustered in metropolitan regions like Philadelphia and Pittsburgh, so most vulnerable tracts still have relatively good proximity.\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\n# Aggregate statistics by county\npa_counties_proj <- st_transform(pa_counties, 3365)\n\nvul_counties <- pa_counties_proj %>%\n  st_join(vulnerable_tracts_proj) %>%\n  group_by(GEOID = GEOID.x, Name = NAMELSAD.x) %>%\n  summarize(\n    n_vulnerable = n(),\n    n_underserved = sum(underserved, na.rm = TRUE),\n    pct_underserved = round(100 * n_underserved / n_vulnerable, 1),\n    avg_hospital_dist = mean(nearest_hospital_dist, na.rm = TRUE),\n    total_vul_pop = sum(total_popE, na.rm = TRUE)\n  )\n\ntop5_pct_underserved <- vul_counties %>%\n  ungroup() %>%\n  arrange(desc(pct_underserved)) %>%\n  slice(1:5)\n\ntop_vul_pop <- vul_counties %>%\n  ungroup() %>%\n  arrange(desc(total_vul_pop)) %>%\n  slice(1:1)\n```\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\n  - Columbia, Perry, Clinton, Monroe, Dauphin.\n- Which counties have the most vulnerable people living far from hospitals?\n  - Allegheny.\n- Are there any patterns in where underserved counties are located?\n  - Underserved counties are concentrated in central and north-central Pennsylvania, which are primarily rural and geographically isolated, while urban counties with major healthcare systems are less underserved in terms of hospital access.\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\npriority_counties <- vul_counties %>%\n  st_drop_geometry() %>%\n  ungroup() %>%\n  filter(pct_underserved >= 20) %>%\n  arrange(desc(total_vul_pop)) %>%\n  slice(1:10)  %>%\n  select(\n    County = Name,\n    `# Vulnerable Tracts` = n_vulnerable,\n    `# Underserved Tracts` = n_underserved,\n    `% Underserved Tracts` = pct_underserved,\n    `Avg. Distance to Hospital (mi)` = avg_hospital_dist,\n    `Total Vulnerable Population` = total_vul_pop\n  )\n\nkable(\n  priority_counties,\n  caption = \"Top 10 PA Counties for Prioritized Healthcare Investment (by vulnerable population in tracts ≥20% underserved, >15 miles from hospitals)\",\n  format.args = list(big.mark = \",\"),\n  digits = 1\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 PA Counties for Prioritized Healthcare Investment (by vulnerable population in tracts ≥20% underserved, >15 miles from hospitals)\n\n|County            | # Vulnerable Tracts| # Underserved Tracts| % Underserved Tracts| Avg. Distance to Hospital (mi)| Total Vulnerable Population|\n|:-----------------|-------------------:|--------------------:|--------------------:|------------------------------:|---------------------------:|\n|Clearfield County |                  10|                    3|                 30.0|                           12.8|                      34,060|\n|Franklin County   |                   5|                    1|                 20.0|                            4.8|                      19,158|\n|Lycoming County   |                   6|                    2|                 33.3|                            9.9|                      16,971|\n|Armstrong County  |                   5|                    1|                 20.0|                            8.4|                      15,467|\n|Juniata County    |                   5|                    2|                 40.0|                           13.6|                      15,070|\n|Tioga County      |                   4|                    1|                 25.0|                            9.7|                      14,234|\n|Elk County        |                   6|                    2|                 33.3|                           13.6|                      14,173|\n|Mifflin County    |                   5|                    1|                 20.0|                           10.1|                      13,470|\n|Clarion County    |                   5|                    2|                 40.0|                           12.4|                      12,929|\n|Bradford County   |                   3|                    1|                 33.3|                            9.6|                      12,646|\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\nggplot() +\n  geom_sf(data = vul_counties, aes(fill = pct_underserved), color = \"white\", size = 0.5) +\n  geom_sf(data = hospitals_proj, color = \"lightblue\", size = 0.5) +\n  scale_fill_viridis_c(option = \"plasma\", name = \"% of Vulnerable Tracts Underserved\") +\n  labs(\n    title = \"Healthcare Access Challenges in Pennsylvania\",\n    subtitle = \"Blue points = Hospitals, Counties shaded by % vulnerable tracts >15 miles from nearest hospital\",\n    caption = \"Data: ACS 2022 5-year estimates, PA hospitals dataset\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](Yang_Henry_Assignment2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\nunderserved_vul_tracts <- vulnerable_tracts_proj %>%\n  filter(underserved)\n\nggplot() +\n  geom_sf(data = pa_counties_proj, fill = \"white\", color = \"grey\", size = 0.5) +\n  geom_sf(data = hospitals_proj, color = \"red\", size = 0.5) +\n  geom_sf(data = underserved_vul_tracts, fill = \"yellow\", color = \"grey\", size = 0.5) +\n  labs(\n    title = \"Healthcare Access Challenges in Pennsylvania\",\n    subtitle = \"Blue points = Hospitals, Counties shaded by % vulnerable tracts >15 miles from nearest hospital\",\n    caption = \"Data: ACS 2022 5-year estimates, PA hospitals dataset\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](Yang_Henry_Assignment2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\nggplot(vulnerable_tracts_proj)+\n  aes(x = nearest_hospital_dist) +\n  geom_histogram(\n    binwidth = 1, \n    fill = \"orange\", \n    color = \"white\", \n    alpha = 0.7\n  ) +\n  geom_vline(aes(xintercept = 15), color = \"blue\", linetype = \"dashed\", size = 1) +\n  labs(\n    title = \"Distribution of Distances to Nearest Hospital for Vulnerable Tracts\",\n    subtitle = \"Dashed line indicates 15-mile underserved threshold\",\n    x = \"Distance to Nearest Hospital (miles)\",\n    y = \"Number of Vulnerable Tracts\",\n    caption = \"Data: ACS 2022 5-year, PA hospitals dataset\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Yang_Henry_Assignment2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\npolling <- st_read(here(\"data\", \"polling_places.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `polling_places' from data source \n  `/Users/henryyang/Desktop/MasterStuff/CPLN5920/Code/portfolio-setup-henryyzh1/Labs/lab_2/data/polling_places.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1703 features and 10 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.26784 ymin: 39.8978 xmax: -74.9667 ymax: 40.12983\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nbus <- st_read(here(\"data\", \"septa_bus.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Spring_2025_Stop_Summary_(Bus)' from data source \n  `/Users/henryyang/Desktop/MasterStuff/CPLN5920/Code/portfolio-setup-henryyzh1/Labs/lab_2/data/septa_bus.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 18219 features and 15 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.83469 ymin: 39.80381 xmax: -74.7542 ymax: 40.33401\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nmetro <- st_read(here(\"data\", \"septa_metro.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Highspeed_Stations' from data source \n  `/Users/henryyang/Desktop/MasterStuff/CPLN5920/Code/portfolio-setup-henryyzh1/Labs/lab_2/data/septa_metro.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 74 features and 5 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.35358 ymin: 39.90543 xmax: -75.07788 ymax: 40.11349\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nrail <- st_read(here(\"data\", \"septa_rail.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Regional_Rail_Stations' from data source \n  `/Users/henryyang/Desktop/MasterStuff/CPLN5920/Code/portfolio-setup-henryyzh1/Labs/lab_2/data/septa_rail.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 156 features and 6 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.7627 ymin: 39.67018 xmax: -74.75399 ymax: 40.3062\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ntrolley <- st_read(here(\"data\", \"septa_trolley.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Trolley_Stations' from data source \n  `/Users/henryyang/Desktop/MasterStuff/CPLN5920/Code/portfolio-setup-henryyzh1/Labs/lab_2/data/septa_trolley.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 60 features and 5 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.394 ymin: 39.90667 xmax: -75.16256 ymax: 39.96216\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nphl_tracts <- tracts(state = \"PA\", county = \"Philadelphia\", cb = TRUE)\n\nphl_acs_vars <- c(\n  total_pop = \"B01003_001\",\n  age65_66_m = \"B01001_020\",\n  age67_69_m = \"B01001_021\",\n  age70_74_m = \"B01001_022\",\n  age75_79_m = \"B01001_023\",\n  age80_84_m = \"B01001_024\",\n  age85_over_m = \"B01001_025\",\n  age65_66_f = \"B01001_044\",\n  age67_69_f = \"B01001_045\",\n  age70_74_f = \"B01001_046\",\n  age75_79_f = \"B01001_047\",\n  age80_84_f = \"B01001_048\",\n  age85_over_f = \"B01001_049\",\n  total_disab = \"C18108_001\",\n  disabled_pop = \"C18108_002\"\n)\n\nphl_acs <- get_acs(\n  geography = \"tract\",\n  variables = phl_acs_vars,\n  state = \"PA\",\n  county = \"Philadelphia\",\n  year = 2022,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nphl_acs <- phl_acs %>%\n  mutate(\n    pop65plusE = age65_66_mE + age67_69_mE + age70_74_mE + age75_79_mE +\n                 age80_84_mE + age85_over_mE +\n                 age65_66_fE + age67_69_fE + age70_74_fE + age75_79_fE +\n                 age80_84_fE + age85_over_fE,\n    pct_elderly = 100 * pop65plusE / total_popE,\n    pct_disabled = 100 * disabled_popE / total_disabE\n  )\n\nphl_tracts_acs <- phl_tracts %>%\n  left_join(phl_acs, by = \"GEOID\")\n\nst_crs(polling)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(bus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(metro)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(rail)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(trolley)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(phl_tracts_acs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: NAD83 \n  wkt:\nGEOGCRS[\"NAD83\",\n    DATUM[\"North American Datum 1983\",\n        ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4269]]\n```\n\n\n:::\n\n```{.r .cell-code}\nsepta_stops <- bind_rows(\n  bus %>% mutate(mode = \"Bus\"),\n  metro %>% mutate(mode = \"Metro\"),\n  rail %>% mutate(mode = \"Regional Rail\"),\n  trolley %>% mutate(mode = \"Trolley\")\n)\n\npolling <- st_transform(polling, 3365)\nsepta_stops <- st_transform(septa_stops, 3365)\nphl_tracts_acs <- st_transform(phl_tracts_acs, 3365)\n\nnrow(polling)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1703\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(septa_stops)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18509\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(phl_tracts_acs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 408\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\n  - I chose to analyze polling place accessibility for elderly and disabled populations in Philadelphia County. This topic connects spatial infrastructure and social equity, examining whether polling places are located in areas that are reachable by public transit for voters who may have mobility challenges.\n- What is the data source and date?\n  - Polling Places (2014): https://opendataphilly.org/datasets/polling-places/\n  - SEPTA Stops (2025 Spring): https://wwww.septa.org/open-data/\n  - Demographics and Census Tracts: U.S. Census Bureau’s 2022 ACS 5-Year Estimates\n- How many features does it contain?\n  - Polling Places: 1703 points.\n  - SEPTA Stops: 18509 points.\n  - Census Tracts: 408 polygons.\n- What CRS is it in? Did you need to transform it?\n  - The original files were in geographic coordinates WGS 1984 (EPSG:4326). All layers were projected to EPSG:3365 (NAD83(HARN) / Pennsylvania State Mapping System, feet) for accurate distance and buffer analysis.\n\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\n** - Are polling places in Philadelphia County equitably accessible for elderly and disabled residents via public transit?**\n\n**Examples:**\n- \"Do vulnerable tracts have adequate public transit access to hospitals?\"\n- \"Are EMS stations appropriately located near vulnerable populations?\"\n- \"Do areas with low vehicle access have worse hospital access?\"\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\npolling_buf <- st_buffer(polling, dist = 1320)\nstops_buf <- st_buffer(septa_stops, dist = 1320)\naccessible_area <- st_intersection(polling_buf, stops_buf)\n\naccessible_area_union <- accessible_area %>%\n  st_union() %>%\n  st_make_valid() %>%\n  st_sf()\n\nhit <- st_intersects(phl_tracts_acs, accessible_area_union, sparse = FALSE)[,1]\n\nphl_tract_access <- phl_tracts_acs %>%\n  mutate(accessible = hit)\n\nphl_tract_summary <- phl_tract_access %>%\n  st_drop_geometry() %>%\n  group_by(accessible) %>%\n  summarise(\n    total_pop = sum(total_popE, na.rm = TRUE),\n    elderly_pop = sum(pop65plusE, na.rm = TRUE),\n    disabled_pop = sum(disabled_popE, na.rm = TRUE)\n  )\n\nggplot() +\n  geom_sf(data = phl_tracts_acs, fill = \"white\", color = \"grey\", size = 0.5) +\n  geom_sf(data = polling, color = \"red\", size = 0.1) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](Yang_Henry_Assignment2_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\ninaccessible_tracts <- phl_tract_access %>%\n  filter(accessible == FALSE)\n\nggplot() +\n  geom_sf(data = phl_tract_access, fill = \"white\", color = \"grey\", size = 0.5) +\n  geom_sf(data = inaccessible_tracts, fill = \"red\", color = \"grey\", size = 0.5) +\n  geom_sf(data = accessible_area_union, fill = \"yellow\", color = \"grey\", size = 0.5) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](Yang_Henry_Assignment2_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\nThe analysis used a 0.25-mile buffer to represent a reasonable walking distance for elderly and disabled residents to reach polling places and nearby transit stops. By intersecting the polling-place and transit buffers, I identified areas that are walkable from both a polling place and a transit stop. A spatial join with census tracts showed that nearly all residential tracts in Philadelphia are accessible, with only four non-residential tracts outside the buffer area. This indicates that Philadelphia’s dense urban layout and extensive SEPTA network provide strong transit-based access to polling places for vulnerable populations.\n\n\n## Finally - A few comments about your incorporation of feedback!\n\nAfter receiving feedback on my first assignment, I will make several improvements to this report, removing unnecessary instruction text and private key information, and keeping only the essential tables and visualizations to maintain a clear and focused narrative.\n\n---",
    "supporting": [
      "Yang_Henry_Assignment2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}